export type Location = {
    id: number;
    name: string;
    address: string;
    hours: string;
    city: string;
    province: string;
};

export const locations: Location[] = [
    { id: 1, name: 'Guanajay', address: 'Calle 23 e/ 30 y 32', hours: '09:00 - 16:30', city: 'Guanajay', province: 'Artemisa' },
    { id: 2, name: 'Bauta', address: 'Ave. 251 No. 13813 e/ 138 y 140', hours: '09:00 - 16:30', city: 'Bauta', province: 'Artemisa' },
    { id: 3, name: 'Mariel', address: 'Carretera Guanajay, Km 114', hours: '09:00 - 16:30', city: 'Mariel', province: 'Artemisa' },
    { id: 4, name: 'San Cristóbal', address: 'Calle Maceo No. 102', hours: '09:00 - 16:30', city: 'San Cristóbal', province: 'Artemisa' },
    { id: 5, name: 'Santa Lucia', address: 'Carretera Central Este, km 4½, Jayamá', hours: '08:30 - 17:30', city: 'Camagüey', province: 'Camagüey' },
    { id: 6, name: 'Jayamá', address: 'Avenida Finlay Km. 7 1/2', hours: '09:00 - 16:30', city: 'Camagüey', province: 'Camagüey' },
    { id: 7, name: 'Florida', address: 'Carretera Central, km 532', hours: '09:00 - 16:30', city: 'Florida', province: 'Camagüey' },
    { id: 8, name: 'Aeropuerto Camagüey', address: 'Carretera Nuevitas, Km 7.5', hours: '09:00 - 16:30', city: 'Camagüey', province: 'Camagüey' },
    { id: 9, name: 'Hotel Ciego de Ávila', address: 'Carretera de Ceballo, km 2 ½', hours: '08:30 - 19:30', city: 'Ciego de Ávila', province: 'Ciego de Ávila' },
    { id: 10, name: 'Parque Echavarria Morón', address: 'Libertad esq. Martí', hours: '08:00 - 17:00', city: 'Morón', province: 'Ciego de Ávila' },
    { id: 11, name: 'Ciego de Ávila 24 Horas', address: 'Carretera a Ceballo km 1 ½', hours: '09:00 - 16:30', city: 'Ciego de Ávila', province: 'Ciego de Ávila' },
    { id: 12, name: 'Rotonda Cayo Coco', address: 'Km 8, Via a Cayo Guillermo, Cayo Coco', hours: '09:00 - 16:30', city: 'Morón', province: 'Ciego de Ávila' },
    { id: 13, name: 'Hotel Melia Cayo Coco', address: 'Cayo Coco', hours: '09:00 - 16:30', city: 'Morón', province: 'Ciego de Ávila' },
    { id: 14, name: 'Hotel Melia Costa Rey', address: 'Carretera Cayo Guillermo, Cayo Coco', hours: '09:00 - 16:30', city: 'Morón', province: 'Ciego de Ávila' },
    { id: 15, name: 'Hotel Daiquiri', address: 'Carretera Cayo Guillermo, Cayo Coco', hours: '09:00 - 16:30', city: 'Morón', province: 'Ciego de Ávila' },
    { id: 16, name: 'Aguada de Pasajeros', address: 'Carretera Circuito Sur s/n', hours: '09:00 - 16:30', city: 'Aguada de Pasajeros', province: 'Cienfuegos' },
    { id: 17, name: 'Aeropuerto Cienfuegos', address: 'Carretera Caonao', hours: '09:00 - 16:30', city: 'Cienfuegos', province: 'Cienfuegos' },
    { id: 18, name: 'Hotel Unión', address: 'Calle 31 esq. 54', hours: '09:00 - 16:30', city: 'Cienfuegos', province: 'Cienfuegos' },
    { id: 19, name: 'Punta Gorda', address: 'Avenida 10 entre 39 y 41 #3908, Punta Gorda', hours: '09:00 - 16:30', city: 'Cienfuegos', province: 'Cienfuegos' },
    { id: 20, name: 'Hotel Marea de Portillo', address: 'Carretera a Marea del Portillo, Km. 12.5', hours: '09:00 - 16:30', city: 'Pilón', province: 'Granma' },
    { id: 21, name: 'Hotel Guacanayabo', address: 'Ave Camilo Cienfuegos', hours: '09:00 - 16:30', city: 'Manzanillo', province: 'Granma' },
    { id: 22, name: 'Hotel Sierra Maestra', address: 'Carretera Central, km 7 ½', hours: '09:00 - 16:30', city: 'Bayamo', province: 'Granma' },
    { id: 23, name: 'Hotel Guantánamo', address: 'Plaza Mariana Grajales, Ahogados y 13 Norte', hours: '09:00 - 16:30', city: 'Guantánamo', province: 'Guantánamo' },
    { id: 24, name: 'Centro Baracoa', address: 'Maceo esq. a Rafael Trejo', hours: '09:00 - 16:30', city: 'Baracoa', province: 'Guantánamo' },
    { id: 25, name: 'Guardalavaca', address: 'Calle 2, Playa Guardalavaca', hours: '09:00 - 16:30', city: 'Banes', province: 'Holguín' },
    { id: 26, name: 'Aeropuerto Holguin', address: 'Carretera Central vía Bayamo, km 15', hours: '08:00 - 20:00', city: 'Holguín', province: 'Holguín' },
    { id: 27, name: 'Avenida Holguin', address: 'Ave. Jesús Menéndez esquina Ave. Internacionalistas', hours: '08:30 - 17:30', city: 'Holguín', province: 'Holguín' },
    { id: 28, name: 'Gibara', address: 'Donato Mármol No. 1 Plaza El Fuerte', hours: '09:00 - 16:30', city: 'Gibara', province: 'Holguín' },
    { id: 29, name: 'Aeropuerto - Terminal 2', address: 'Avenida Rancho Boyeros', hours: '08:30 - 20:00', city: 'Boyeros', province: 'La Habana' },
    { id: 30, name: 'Aeropuerto - Terminal 3', address: 'Avenida Rancho Boyeros', hours: '00:01 - 23:59', city: 'Boyeros', province: 'La Habana' },
    { id: 31, name: '5ta y 84', address: '5ta Avenida y 92, Miramar', hours: '09:00 - 20:00', city: 'Playa', province: 'La Habana' },
    { id: 32, name: 'Hotel Comodoro', address: 'Calle 3ra entre 82 y 84,Miramar', hours: '08:30 - 19:00', city: 'Playa', province: 'La Habana' },
    { id: 33, name: 'Marina Hemingway', address: 'Calle 248 y 5ta Avenida', hours: '08:30 - 19:30', city: 'Playa', province: 'La Habana' },
    { id: 34, name: '3ra y Paseo (24 Horas)', address: 'Línea esquina Malecón, Vedado', hours: '00:01 - 23:59', city: 'Plaza de la Revolución', province: 'La Habana' },
    { id: 35, name: 'Hotel Capri', address: 'Calle 21 e/ N y O, Vedado', hours: '09:00 - 16:30', city: 'Plaza de la Revolución', province: 'La Habana' },
    { id: 36, name: 'Guanabo, Gran Via', address: 'Trocadero 55 e/ Prado y Zulueta', hours: '09:00 - 16:30', city: 'Habana Vieja', province: 'La Habana' },
    { id: 37, name: 'Guanabo, Rotonda', address: 'Vía Blanca y Rotonda de Guanabo', hours: '09:00 - 16:30', city: 'Habana del Este', province: 'La Habana' },
    { id: 38, name: 'Kasalta', address: 'Ave. 5ta. y Calle 2, Miramar', hours: '09:00 - 16:30', city: 'Playa', province: 'La Habana' },
    { id: 39, name: 'Dos Gardenias', address: 'Desamparados no. 166 entre Habana y Compostela', hours: '09:00 - 16:30', city: 'Habana Vieja', province: 'La Habana' },
    { id: 40, name: 'Puerto Padre', address: 'Calle Francisco Varona No. 294 e/ Joaquín Agüero y Ángel Guardia', hours: '09:00 - 16:30', city: 'Las Tunas', province: 'Las Tunas' },
    { id: 41, name: 'Aeropuerto Juan Gualberto Gómez', address: 'Carretera a Regalito, km 5½', hours: '08:00 - 20:00', city: 'Varadero', province: 'Matanzas' },
    { id: 42, name: 'Hotel Iberostar Varadero', address: 'Km 16, Carretera Las Morlas, Punta Hicacos', hours: '08:30 - 19:00', city: 'Varadero', province: 'Matanzas' },
    { id: 43, name: 'Varadero ciudad', address: 'Calle 36 y Autopista', hours: '08:30 - 19:00', city: 'Varadero', province: 'Matanzas' },
    { id: 44, name: 'Cárdenas', address: 'Calle Pellimonje e/ 21 y 22, Rpto. Fructuoso Rodríguez', hours: '09:00 - 16:30', city: 'Cárdenas', province: 'Matanzas' },
    { id: 45, name: 'Safari', address: 'Carretera del Petróleo, Guásimas', hours: '09:00 - 16:30', city: 'Cárdenas', province: 'Matanzas' },
    { id: 46, name: 'Colón', address: 'Carretera Central', hours: '09:00 - 16:30', city: 'Colón', province: 'Matanzas' },
    { id: 47, name: 'Jagüey Grande', address: 'Calle 15 e/ 58 y 60', hours: '09:00 - 16:30', city: 'Jagüey Grande', province: 'Matanzas' },
    { id: 48, name: 'Jovellanos', address: 'Carretera Central a Perico e/ 31 y Final', hours: '09:00 - 16:30', city: 'Jovellanos', province: 'Matanzas' },
    { id: 49, name: 'Martí', address: 'Maceo s/n e/ Cosme de la Torriente y Camilo Cienfuegos', hours: '09:00 - 16:30', city: 'Martí', province: 'Matanzas' },
    { id: 50, name: 'Ceiba Mocha', address: 'Calle Martí final e/ Carretera Central y Línea', hours: '09:00 - 16:30', city: 'Matanzas', province: 'Matanzas' },
    { id: 51, name: 'Matanzas', address: 'Calzada General Betancourt, e/ Jagüey y Muelle, esq. a Playa', hours: '09:00 - 16:30', city: 'Matanzas', province: 'Matanzas' },
    { id: 52, name: 'Unión de Reyes', address: 'Calle Calixto García, No. 27, e/ Bartolomé Masó y Jesús Menéndez', hours: '09:00 - 16:30', city: 'Unión de Reyes', province: 'Matanzas' },
    { id: 53, name: 'Aeropuerto Varadero', address: 'Ave. Mártires de Barbados KM 5-6, Finca Cabarroca, Carbonera', hours: '00:01 - 23:59', city: 'Varadero', province: 'Matanzas' },
    { id: 54, name: 'Barlovento Autos', address: 'Santa Marta Centro de Negocios', hours: '09:00 - 16:30', city: 'Varadero', province: 'Matanzas' },
    { id: 55, name: 'Calle 8', address: 'Calle 30 e/ 2da y Autopista Sur', hours: '08:00 - 17:00', city: 'Varadero', province: 'Matanzas' },
    { id: 56, name: 'Hotel Meliá Antillas', address: 'Avenida 1ra esq. 59', hours: '09:00 - 16:30', city: 'Varadero', province: 'Matanzas' },
    { id: 57, name: 'Hotel Meliá Internacional', address: 'Carretera Las Morlas Final Punta Hicaco', hours: '09:00 - 16:30', city: 'Varadero', province: 'Matanzas' },
    { id: 58, name: 'Hotel Palma Real', address: 'Calle 53 y 1ra Ave', hours: '09:00 - 16:30', city: 'Varadero', province: 'Matanzas' },
    { id: 59, name: 'Hotel Playa de Oro', address: 'Carretera Las Morlas', hours: '09:00 - 16:30', city: 'Varadero', province: 'Matanzas' },
    { id: 60, name: 'Jaguey Grande', address: 'Autopista Nacional, Km 144', hours: '09:00 - 16:30', city: 'Jagüey Grande', province: 'Matanzas' },
    { id: 61, name: 'Mediterraneo', address: 'Calle 54 y 1ra Avenida', hours: '09:00 - 16:30', city: 'Varadero', province: 'Matanzas' },
    { id: 62, name: 'Palmeras', address: 'Calle 53 y 1ra Ave', hours: '09:00 - 16:30', city: 'Varadero', province: 'Matanzas' },
    { id: 63, name: 'Playa Girón', address: 'Playa Girón', hours: '09:00 - 16:30', city: 'Ciénaga de Zapata', province: 'Matanzas' },
    { id: 64, name: 'Plaza America', address: 'Centro de Convenciones Plaza América', hours: '09:00 - 16:30', city: 'Varadero', province: 'Matanzas' },
    { id: 65, name: 'Starfisch', address: 'Carretera Las Morlas Km 14', hours: '09:00 - 16:30', city: 'Varadero', province: 'Matanzas' },
    { id: 66, name: 'Tropical', address: 'Avenida 1ra y Calle 21', hours: '09:00 - 16:30', city: 'Varadero', province: 'Matanzas' },
    { id: 67, name: 'Villa Tropico', address: 'Vía Blanca, Km 60, Jibacoa', hours: '09:00 - 16:30', city: 'Santa Cruz del Norte', province: 'Mayabeque' },
    { id: 68, name: 'San José de las Lajas', address: 'Calle 48 e/ 41 y 43', hours: '09:00 - 16:30', city: 'San José de las Lajas', province: 'Mayabeque' },
    { id: 69, name: 'Hotel Pinar del Rio', address: 'Martí y Final Autopista', hours: '09:00 - 20:00', city: 'Pinar del Río', province: 'Pinar del Río' },
    { id: 70, name: 'Viñales', address: 'Calle Salvador Cisneros, No. 140', hours: '09:00 - 16:30', city: 'Viñales', province: 'Pinar del Río' },
    { id: 71, name: 'Herradura', address: 'Cabo San Antonio, La bajada. Municipio San Diego', hours: '09:00 - 16:30', city: 'Sandino', province: 'Pinar del Río' },
    { id: 72, name: 'San Juan y Martínez', address: 'Calle Martí esq. a Libertad', hours: '09:00 - 16:30', city: 'San Juan y Martínez', province: 'Pinar del Río' },
    { id: 73, name: 'Centro Comercial Trinidad', address: 'Ave. Camilo Cienfuegos s/n e A y B', hours: '09:00 - 16:30', city: 'Trinidad', province: 'Sancti Spíritus' },
    { id: 74, name: 'Cupet Trinidad', address: 'Calle Jesús Menéndez No. 2 e/ Agramonte y Honorato del Castillo', hours: '09:00 - 16:30', city: 'Trinidad', province: 'Sancti Spíritus' },
    { id: 75, name: 'Hotel Trinidad del Mar', address: 'Península Ancón', hours: '09:00 - 16:30', city: 'Trinidad', province: 'Sancti Spíritus' },
    { id: 76, name: 'Peninsula Ancon', address: 'Carretera María Aguilar', hours: '09:00 - 16:30', city: 'Trinidad', province: 'Sancti Spíritus' },
    { id: 77, name: 'Sancti Spíritus Bolera', address: 'Ave. Panchito Gómez Toro Final', hours: '09:00 - 16:30', city: 'Sancti Spíritus', province: 'Sancti Spíritus' },
    { id: 78, name: 'Aeropuerto Antonio Maceo', address: 'Carretera Ciudamar, km 2 ½', hours: '00:01 - 23:59', city: 'Santiago de Cuba', province: 'Santiago de Cuba' },
    { id: 79, name: 'Las Americas', address: 'Carretera del Caney y Calle 15, Vista Alegre', hours: '09:00 - 16:30', city: 'Santiago de Cuba', province: 'Santiago de Cuba' },
    { id: 80, name: 'Casa Granda', address: 'Heredia esq. San Pedro', hours: '09:00 - 16:30', city: 'Santiago de Cuba', province: 'Santiago de Cuba' },
    { id: 81, name: 'Hotel Meliá Santiago', address: 'Avenida de las Americas y Calle M', hours: '09:00 - 16:30', city: 'Santiago de Cuba', province: 'Santiago de Cuba' },
    { id: 82, name: 'Aeropuerto Santa Clara', address: 'Carretera Malezas km 11', hours: '08:30 - 17:30', city: 'Santa Clara', province: 'Villa Clara' },
    { id: 83, name: 'Burro Perico', address: 'Pueblo Las Dunas, Pedraplén Cayo Santa María', hours: '09:00 - 16:30', city: 'Caibarién', province: 'Villa Clara' },
    { id: 84, name: 'Remedios', address: 'Máximo Gómez No. 115', hours: '09:00 - 16:30', city: 'Remedios', province: 'Villa Clara' },
];
